# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_artisanaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanaccount',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='artisan_media_location'),
        ),
    ]
