# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 21:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_artisanaccount_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='artisanaccount',
            name='description',
            field=models.CharField(default=datetime.datetime(2017, 10, 31, 21, 1, 56, 766947, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisancategory',
            name='artisan_account',
            field=models.ManyToManyField(to='sellers.ArtisanAccount'),
        ),
    ]
