# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 08:06
from __future__ import unicode_literals

import artisan.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=artisan.models.upload_dir)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=artisan.models.upload_dir)),
                ('address', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=11)),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('managers', models.ManyToManyField(blank=True, related_name='manager_artisans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
