# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 01:01
from __future__ import unicode_literals

import artisan.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanaccount',
            name='banner_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=artisan.models.upload_dir),
        ),
        migrations.AddField(
            model_name='artisanaccount',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=artisan.models.upload_dir),
        ),
    ]
