# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 13:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0002_auto_20171207_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanaccount',
            name='address',
            field=models.CharField(default=datetime.datetime(2017, 12, 8, 13, 56, 39, 762389, tzinfo=utc), max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artisanaccount',
            name='mobile_number',
            field=models.CharField(default=datetime.datetime(2017, 12, 8, 13, 56, 48, 835512, tzinfo=utc), max_length=11),
            preserve_default=False,
        ),
    ]
