# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artisan', '0003_auto_20171208_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanaccount',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
