# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_auto_20171031_2101'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('artisan', models.ManyToManyField(blank=True, to='sellers.ArtisanAccount')),
            ],
        ),
    ]
