# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1000.0, max_digits=100, null=True),
        ),
    ]
