# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0003_curatedskills_myskills_skillrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curatedskills',
            old_name='Skills',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='myskills',
            old_name='skills',
            new_name='skill',
        ),
        migrations.RenameField(
            model_name='skillrating',
            old_name='Skill',
            new_name='skill',
        ),
    ]
