# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0004_auto_20171208_1548'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curatedskills',
            old_name='skill',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='myskills',
            old_name='skill',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='skillrating',
            old_name='skill',
            new_name='skills',
        ),
    ]
