# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-21 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=5000.0, max_digits=100, null=True),
        ),
    ]
