# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 17:18
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20171021_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location=products.models.download_media_location), upload_to=products.models.download_media_location),
        ),
    ]
