# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 17:20
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171022_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/mathemartins/projects/django/servizedey.com/static_cdn/protected'), upload_to=products.models.download_media_location),
        ),
    ]
