# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 21:47
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20171022_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='//servizedey.s3.amazonaws.com/media/protected/'), upload_to=products.models.download_media_location),
        ),
    ]
