# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-22 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20171022_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.download_media_location),
        ),
    ]
